"""Compare HOM and HDK JSONL fixture directories and write a Markdown report."""

import argparse
from collections import Counter
import json
from pathlib import Path
import sys

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from coophou.probe.trace import validate_record


def read_trace(path):
    records = []
    with path.open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            record = json.loads(line)
            try:
                validate_record(record)
            except ValueError as exc:
                raise ValueError(f"{path}:{line_number}: {exc}") from exc
            records.append(record)
    return records


def compact_sequence(records):
    groups = []
    for record in records:
        event = record["event"]
        if groups and groups[-1][0] == event:
            groups[-1][1] += 1
        else:
            groups.append([event, 1])
    rendered = [name if count == 1 else f"{name}×{count}" for name, count in groups]
    if len(rendered) > 30:
        rendered = rendered[:30] + [f"… +{len(groups) - 30} groups"]
    return " → ".join(rendered) or "—"


def escape_cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def compare(hom_directory, hdk_directory):
    hom_files = {path.stem: path for path in hom_directory.glob("*.jsonl")}
    hdk_files = {path.stem: path for path in hdk_directory.glob("*.jsonl")}
    scenarios = sorted(set(hom_files) | set(hdk_files))
    lines = [
        "# Generated Houdini event-probe comparison",
        "",
        "> Generated by `scripts/compare_event_traces.py`; paths are diagnostic, not identity.",
        "",
        "| Scenario | HOM observations | HDK observations | HOM sequence | HDK sequence |",
        "|---|---:|---:|---|---|",
    ]
    for scenario in scenarios:
        hom = read_trace(hom_files[scenario]) if scenario in hom_files else []
        hdk = read_trace(hdk_files[scenario]) if scenario in hdk_files else []
        lines.append(
            "| {} | {} | {} | {} | {} |".format(
                escape_cell(scenario),
                len(hom),
                len(hdk),
                escape_cell(compact_sequence(hom)),
                escape_cell(compact_sequence(hdk)),
            )
        )
    lines.extend(("", "## Event totals", ""))
    for adapter, files in (("HOM", hom_files), ("HDK", hdk_files)):
        counts = Counter()
        for path in files.values():
            counts.update(record["event"] for record in read_trace(path))
        lines.append(f"- {adapter}: " + ", ".join(f"`{name}` × {count}" for name, count in sorted(counts.items())))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("hom_directory", type=Path)
    parser.add_argument("hdk_directory", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    report = compare(args.hom_directory, args.hdk_directory)
    if args.output:
        args.output.write_text(report, encoding="utf-8", newline="\n")
    else:
        print(report, end="")


if __name__ == "__main__":
    main()
